/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as InsightsInsightIdRouteImport } from './routes/insights/$insightId'
import { Route as MapLabIndexRouteImport } from './routes/map-lab/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as ModelsModelIdRouteImport } from './routes/models/$modelId'
import { Route as ModelsIndexesRouteImport } from './routes/models/indexes'
import { Route as MyModelsIndexRouteImport } from './routes/my-models/index'
import { Route as ReaderIndexRouteImport } from './routes/reader/index'
import { Route as VersesIndexRouteImport } from './routes/verses/index'
import { Route as VersesVerseIdRouteImport } from './routes/verses/$verseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsInsightIdRoute = InsightsInsightIdRouteImport.update({
  id: '/insights/$insightId',
  path: '/insights/$insightId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapLabIndexRoute = MapLabIndexRouteImport.update({
  id: '/map-lab/',
  path: '/map-lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexesRoute = ModelsIndexesRouteImport.update({
  id: '/models/indexes',
  path: '/models/indexes',
  getParentRoute: () => rootRouteImport,
} as any)
const MyModelsIndexRoute = MyModelsIndexRouteImport.update({
  id: '/my-models/',
  path: '/my-models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderIndexRoute = ReaderIndexRouteImport.update({
  id: '/reader/',
  path: '/reader/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesIndexRoute = VersesIndexRouteImport.update({
  id: '/verses/',
  path: '/verses/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesVerseIdRoute = VersesVerseIdRouteImport.update({
  id: '/verses/$verseId',
  path: '/verses/$verseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/framework': typeof FrameworkRoute
  '/sources': typeof SourcesRoute
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/indexes': typeof ModelsIndexesRoute
  '/verses/$verseId': typeof VersesVerseIdRoute
  '/insights/': typeof InsightsIndexRoute
  '/map-lab/': typeof MapLabIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/my-models/': typeof MyModelsIndexRoute
  '/reader/': typeof ReaderIndexRoute
  '/verses/': typeof VersesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/framework': typeof FrameworkRoute
  '/sources': typeof SourcesRoute
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/indexes': typeof ModelsIndexesRoute
  '/verses/$verseId': typeof VersesVerseIdRoute
  '/insights': typeof InsightsIndexRoute
  '/map-lab': typeof MapLabIndexRoute
  '/models': typeof ModelsIndexRoute
  '/my-models': typeof MyModelsIndexRoute
  '/reader': typeof ReaderIndexRoute
  '/verses': typeof VersesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/framework': typeof FrameworkRoute
  '/sources': typeof SourcesRoute
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/indexes': typeof ModelsIndexesRoute
  '/verses/$verseId': typeof VersesVerseIdRoute
  '/insights/': typeof InsightsIndexRoute
  '/map-lab/': typeof MapLabIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/my-models/': typeof MyModelsIndexRoute
  '/reader/': typeof ReaderIndexRoute
  '/verses/': typeof VersesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/framework'
    | '/sources'
    | '/insights/$insightId'
    | '/models/$modelId'
    | '/models/indexes'
    | '/verses/$verseId'
    | '/insights/'
    | '/map-lab/'
    | '/models/'
    | '/my-models/'
    | '/reader/'
    | '/verses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/framework'
    | '/sources'
    | '/insights/$insightId'
    | '/models/$modelId'
    | '/models/indexes'
    | '/verses/$verseId'
    | '/insights'
    | '/map-lab'
    | '/models'
    | '/my-models'
    | '/reader'
    | '/verses'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/framework'
    | '/sources'
    | '/insights/$insightId'
    | '/models/$modelId'
    | '/models/indexes'
    | '/verses/$verseId'
    | '/insights/'
    | '/map-lab/'
    | '/models/'
    | '/my-models/'
    | '/reader/'
    | '/verses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  FrameworkRoute: typeof FrameworkRoute
  SourcesRoute: typeof SourcesRoute
  InsightsInsightIdRoute: typeof InsightsInsightIdRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  ModelsIndexesRoute: typeof ModelsIndexesRoute
  VersesVerseIdRoute: typeof VersesVerseIdRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  MapLabIndexRoute: typeof MapLabIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  MyModelsIndexRoute: typeof MyModelsIndexRoute
  ReaderIndexRoute: typeof ReaderIndexRoute
  VersesIndexRoute: typeof VersesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$insightId': {
      id: '/insights/$insightId'
      path: '/insights/$insightId'
      fullPath: '/insights/$insightId'
      preLoaderRoute: typeof InsightsInsightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-lab/': {
      id: '/map-lab/'
      path: '/map-lab'
      fullPath: '/map-lab/'
      preLoaderRoute: typeof MapLabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/indexes': {
      id: '/models/indexes'
      path: '/models/indexes'
      fullPath: '/models/indexes'
      preLoaderRoute: typeof ModelsIndexesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-models/': {
      id: '/my-models/'
      path: '/my-models'
      fullPath: '/my-models/'
      preLoaderRoute: typeof MyModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/': {
      id: '/reader/'
      path: '/reader'
      fullPath: '/reader/'
      preLoaderRoute: typeof ReaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses/': {
      id: '/verses/'
      path: '/verses'
      fullPath: '/verses/'
      preLoaderRoute: typeof VersesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses/$verseId': {
      id: '/verses/$verseId'
      path: '/verses/$verseId'
      fullPath: '/verses/$verseId'
      preLoaderRoute: typeof VersesVerseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  FrameworkRoute: FrameworkRoute,
  SourcesRoute: SourcesRoute,
  InsightsInsightIdRoute: InsightsInsightIdRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  ModelsIndexesRoute: ModelsIndexesRoute,
  VersesVerseIdRoute: VersesVerseIdRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  MapLabIndexRoute: MapLabIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  MyModelsIndexRoute: MyModelsIndexRoute,
  ReaderIndexRoute: ReaderIndexRoute,
  VersesIndexRoute: VersesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
